### ISSUE TITLE
creat a new bagfile

### ISSUE THREAD

**Issue by sunt40** [davidmball/ratslam#13]
$rostopic echo <path/to/my/robot/camera> | rostopic pub <my_robot>/camera/image sensor_msgs/CompressedImage &
$rostopic echo <path/to/my/robot/odom> | rostopic pub <my_robot>/odom nav_msgs/Odometry &
$rosbag record -O <my_robot>.bag <my_robot>/camera/image <my_robot>/odom
I type these code but can't creat a new bagfile .What shoule I do ?

**Comment by scott--** [comment]
I need more information to be able to diagnose this. Does one of the lines have an error? Or is it just that the bagfile is not working with ratslam?

Looking at the irat_aus_28112011.bag the following topics are important:


```
types:       geometry_msgs/PoseStamped   [d3812c3cbc69362b77dc0b19b345f8f5]
             nav_msgs/Odometry           [cd5e73d190d741a2f92e81eda573aca7]
                ...

topics:      /irat_red/camera/image/compressed   16657 msgs    : sensor_msgs/CompressedImage
             /irat_red/odom                      16658 msgs    : nav_msgs/Odometry
                ...
```

Note that the images are actually at /irat_red/camera/image/compressed. This is because ratslam uses image_transport (https://wiki.ros.org/image_transport)

The combination of this subscription (from src/main_lv.cpp):
`  image_transport::ImageTransport it(node);
  image_transport::Subscriber sub = it.subscribe(topic_root + "/camera/image", 0, boost::bind(image_callback, _1, &pub_vt));
`

And this argument in the launch files (irataus.launch):
`_image_transport:=compressed`

Causes ratslam to use <topic_root>/camera/image/compressed

You might need to change these settings depending on the format of your images.

**Comment by sunt40** [comment]
My problems is that: 
`rostopic echo <path/to/my/robot/camera> | rostopic pub <my_robot>/camera/image sensor_msgs/CompressedImage &
rostopic echo <path/to/my/robot/odom> | rostopic pub <my_robot>/odom nav_msgs/Odometry &`
When I run it,the fault is  bash: 未预期的符号 `|' 附近有语法错误.
I'm sorry I am so stupid . But I really want to know and implement this code .
Could you please type your lines about creating a bag file for ratslam ?

**Comment by scott--** [comment]
In the readme, we use <> as placeholders. The lines given are for converting from your **already publishing robot** to the format that we need for ratslam. You need to substitute <path/to/my/robot/camera> and <path/to/my/robot/odom> with the topic that your robot is already publishing on. You cannot have < or > in the lines you give to bash, because they have a special meaning.

What are you trying to do?
- If you already have a robot publishing compressed images and odometry in this format these lines will work.
- If you're just trying to create a bag file from existing data have a look here: https://wiki.ros.org/rosbag/Code%20API#Python_API

Here's some sample code:
```
import rosbag
import glob
from PIL import Image
import io
from sensor_msgs import msg as sm
from nav_msgs import msg as nm

import rospy
import time


bag = rosbag.Bag("test_for_ratslam.bag", "w")

pictures = glob.glob("/directory/with/pictures/*.png")
pictures.sort()

elapsed_ms = 0.

for i, picture in enumerate(pictures):
    img = Image.open(picture).convert("RGB")
    img_bytes = io.BytesIO()
    img.save(img_bytes, format="jpeg")
    img_bytes.seek(0)

    ros_image = sm.CompressedImage()
    ros_image.header.stamp = rospy.Time.from_sec(elapsed_ms)

    ros_image.data = img_bytes.read()

    # write images on this topic
    bag.write("/my_robot/camera/image/compressed", ros_image)

    ros_odom = nm.Odometry()
    ros_odom.header.stamp = rospy.Time.from_sec(elapsed_ms)

    # linear velocity m/s
    ros_odom.twist.twist.linear.x = 0.1

    # angular velocity r/s
    ros_odom.twist.twist.angular.z = 0.1

    # write odom on this topic
    bag.write("/my_robot/odom", ros_odom)

    # next image is 1 s in the future
    elapsed_ms += 1.

    ros_image.header.seq += 1
    ros_odom.header.seq += 1

bag.close()
```

**Comment by sunt40** [comment]
Thanks for your patience ! That's great!
